-- keymaps/obsidian.lua
local map = vim.keymap.set

-- Visual selections (press V first)
map("n", "<leader>db", "i[", { desc = "Insert [" })
map("n", "<leader>dk", "i[[]]<Esc>hi", { desc = "Wrap with [[link]]" })
map("n", "<leader>dvs", "i```dataview<Esc>o", { desc = "Start dataview" })
map("n", "<leader>dve", "o```", { desc = "End dataview" })
map("n", "<leader>px", "o#### Example:<Esc>o", { desc = "Insert Example" })
map("n", "<leader>ph", "I### <Esc>", { desc = "Insert ###" })
map("n", "<leader>pg", "o### ", { desc = "Insert ### below" })
map("n", "<leader>pn", "o#### Note:<Esc>o", { desc = "Insert Note" })
map("n", "<leader>pt", "o## Tips & Hints:<Esc>o", { desc = "Insert Tips" })
map("n", "<leader>pl", "o## Learning:<Esc>o", { desc = "Insert Learning" })
map("n", "<leader>pk", "o## Key Concepts:<Esc>o", { desc = "Insert Concepts" })
map("n", "<leader>pd", "o ---<Esc>o", { desc = "Insert Divider" })
map("n", "<leader>pf", "o#### For more info:<Esc>o[[]]<Esc>hi", { desc = "Insert info" })
map("n", "<leader>pe", "o## Explaining:<Esc>o", { desc = "Insert Explaining" })
map("n", "<leader>poo", "o----------------<Esc>oOutput:<Esc>o", { desc = "Insert Output" })
map("n", "<leader>poi", "0i - <Esc>", { desc = "Insert bullet" })
map("n", "<leader>pco", "o```<CR><Esc>o```<Esc>kkO<Esc>i", { desc = "Insert code block" })
map("n", "<leader>pcv", "o```Vim<CR><Esc>o```<Esc>kkO<Esc>o", { desc = "Insert Vim block" })

-- date/time helper (still normal mode makes more sense)
map("n", "<leader>pcd", function()
  local date = os.date("@%y-%m-%d-%a-%H-%M")
  vim.api.nvim_put({ "(" .. date .. ")" }, "c", true, true)
  vim.cmd("normal! F)a")
  vim.cmd("startinsert")
end, { desc = "Insert date/time" })
